/**
 * Created by code on 2018/6/19.
 */
var filePath = {};
if(!PRODUCTION){
    filePath = {
        index:'../html/index.html',
        login:'../html/login.html',
        unitManagement:'../html/unitManagement.html',
        projectsManagement:'../html/projectsManagement.html',
        compliance:'../html/compliance.html',
        wireless:'../html/wirelessAnalysis.html',
        pdf:'../lib/pdf/web/viewer.html',
        documentList:{
            '100':'../html/checkNotice.html',//信息安全等级保护监督检查通知书
            '7':'../html/feedBack.html',//反馈意见
            '5':'../html/levelProtection.html',//信息安全等级保护检查情况通报书
            '4':'../html/penaltyDecision.html',//行政处罚决定书
            '2':'../html/reorganizeNotice.html',//停机整顿通知书
            '3':'../html/reformNotice.html',//信息系统安全等级保护限期整改通知书
            '1':'../html/talkNotice.html',//信息安全等级保护约谈通知书
            '99':'../html/resultConfirm.html'//工控系统安全等级保护检查情况确认书
        },
      license:'../html/licenseManagement.html',
        vulDetail:'../html/vulDetail.html',
        alertList:'../html/alertList.html',
        repositoryList:'../html/repositoryList.html',
        repositoryEdit:'../html/repositoryEdit.html',
        repositoryView:'../html/repositoryView.html',
        questionList:'../html/questionListLayered.html',
        codeExamineEdit:'../html/codeExamineEdit.html',
        assetsReport:'../html/assetsReport.html',
        assetOperate:'../html/assetOperate.html',
        assetOperateDetail:'../html/assetOperateDetail.html',
        topography:'../html/topography.html',
        assetDeepAnalysis:'../html/assetDeepAnalysis.html',
        assetVideoAnalysis:'../html/videoAnalysis.html',
        trafficReport:'../html/trafficReport.html',
        trafficPcap:'../html/pcapList.html',
        complianceReport:'../html/complianceReport.html',
        homeContent:'../html/homeContent.html',
        vulScan:'../html/vulScan.html',
        vulVerifyScan:'../html/vulVerifyScan.html',
        vulResultAnalysis:'../html/vulResultAnalysis.html',
        baseLineExamineSafeDevice:'../html/baseLineExamineSafeDevice.html',
        baseLineExamineNetDevice:'../html/baseLineExamineNetDevice.html',
        user:'../html/users.html',
        logs:'../html/logs.html',
        moreDetail:'../html/vulMoreDetail.html',
        complianceResultSearch:'../html/resultSearch.html',
        ipConfig:'../html/ipConfig.html',
        quickStart:'../html/quickStart.html'
    };
}else{
    filePath = {
        index:'/index',
        login:'/login',
        unitManagement:'/unitManagement',
        projectsManagement:'/projectsManagement',
        compliance:'/compliance',
        pdf:'../lib/pdf/web/viewer.html',
        wireless:'/wirelessAnalysis',
        documentList:{
            '100':'/checkNotice',//信息安全等级保护监督检查通知书
            '7':'/feedBack',//反馈意见
            '5':'/levelProtection',//信息安全等级保护检查情况通报书
            '4':'/penaltyDecision',//行政处罚决定书
            '2':'/reorganizeNotice',//停机整顿通知书
            '3':'/reformNotice',//信息系统安全等级保护限期整改通知书
            '1':'/talkNotice',//信息安全等级保护约谈通知书
            '99':'/resultConfirm'//工控系统安全等级保护检查情况确认书
        },
      license:'/licenseManagement',
        vulDetail:'/vulDetail',
        alertList:'/alertList',
        repositoryList:'/repositoryList',
        repositoryEdit:'/repositoryEdit',
        repositoryView:'/repositoryView',
        //questionList:'/questionList',
        questionList:'/questionListLayered',
        codeExamineEdit:'/codeExamineEdit',
        assetsReport:'/assetsReport',
        assetOperate:'/assetOperate',
        assetOperateDetail:'/assetOperateDetail',
        topography:'/topography',
        assetDeepAnalysis:'/assetDeepAnalysis',
        assetVideoAnalysis:'/videoAnalysis',
        trafficReport:'/trafficReport',
        trafficPcap:'/pcapList',
        complianceReport:'/complianceReport',
        homeContent:'/homeContent',
        vulScan:'/vulScan',
        vulVerifyScan:'/vulVerifyScan',
        vulResultAnalysis:'/vulResultAnalysis',
        baseLineExamineSafeDevice:'/baseLineExamineSafeDevice',
        baseLineExamineNetDevice:'/baseLineExamineNetDevice',
        user:'/users',
        logs:'/logs',
        moreDetail:'/vulMoreDetail',
        complianceResultSearch:'/resultSearch',
        ipConfig:'/ipConfig',
        quickStart:'/quickStart'
    };
}
export {filePath};
